package ca.paulshin.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table VIDEO.
 */
public class DBVideo {

    private Long id;
    /** Not-null value. */
    private String stitle;
    /** Not-null value. */
    private String ytitle;
    /** Not-null value. */
    private String ytid;

    public DBVideo() {
    }

    public DBVideo(Long id) {
        this.id = id;
    }

    public DBVideo(Long id, String stitle, String ytitle, String ytid) {
        this.id = id;
        this.stitle = stitle;
        this.ytitle = ytitle;
        this.ytid = ytid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getStitle() {
        return stitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStitle(String stitle) {
        this.stitle = stitle;
    }

    /** Not-null value. */
    public String getYtitle() {
        return ytitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setYtitle(String ytitle) {
        this.ytitle = ytitle;
    }

    /** Not-null value. */
    public String getYtid() {
        return ytid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setYtid(String ytid) {
        this.ytid = ytid;
    }

}
